### ISSUE TITLE
How can I get the 'cancer.csv' file?

### ISSUE THREAD

**Issue by yangxg** [vishabh123/vishabh#1]
Hi:

I am interested in your [post](https://towardsdatascience.com/building-a-simple-machine-learning-model-on-breast-cancer-data-eca4b3b99fa3), but I can not find the cancer.csv file in the right format. The dataset in the given link are not identical with the dataset shape in your post. Particularly, I can not find the name of each variables. 

Could you kindly provide the cancer.csv file, or some indication on how to process the data?

Thanks!

**Comment by AryaUkunde** [comment]
> Hi:
> 
> I am interested in your [post](https://towardsdatascience.com/building-a-simple-machine-learning-model-on-breast-cancer-data-eca4b3b99fa3), but I can not find the cancer.csv file in the right format. The dataset in the given link are not identical with the dataset shape in your post. Particularly, I can not find the name of each variables.
> 
> Could you kindly provide the cancer.csv file, or some indication on how to process the data?
> 
> Thanks!

Search for the same data on kaggle. It is available there.

**Comment by yangxg** [comment]
OK, thanks!
